common: &common
  adapter: postgresql
  host: 127.0.0.1
  port: 15432
  encoding: unicode
  pool: 5
  username: jimmyhuang
  password:

development:
  <<: *common
  database: cdd_development

test:
  <<: *common
  database: cdd_test

